version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_latest
    environment:
      - TZ=Asia/Shanghai 
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - /e/WWW:/usr/share/nginx/html

  php-fpm:
    image: php-fpm:7.3
    container_name: php_fpm73
    volumes:
      - ./php-fpm/etc:/usr/local/etc
      - /e/WWW:/usr/share/nginx/html
      - ./php/bin/php:/usr/local/bin/php
    ports:
      - 9000:9000
    expose:
      [9000]
    command: "php-fpm"

  mysql:
    network_mode: "bridge"
    image: mysql:latest
    container_name: mysql_latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis_latest
    ports:
      - "6379:6379"